name: build excalidraw

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: create releases
      run: |
        npm install
        yarn build
        ls excalidraw-app/
        echo "######--4#-#3##3##"
        zip -r build.zip excalidraw-app/build/
        gh release create ${{ github.run_number }}.0.0 build.zip
      env:
         GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
